###################################################################
# Welcome to Eduzone Jekyll Theme 
# Developed by https://themeix.com
# Version : 1.0.0
###################################################################

title: Coded Thinking
email: hello@codedthinking.com
description: >- # this means to ignore newlines until "baseurl:"
  Eduzone Responsive Static Jekyll Theme For Blogging.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jekyll-eduzone.netlify.com/" # the base hostname & protocol for your site, e.g. https://example.com


# Site Settings
twitter_username: codedthinking
logo_url: https://cdn.thnk.ng/img/logo/logo-200.png
footer_logo_url: https://cdn.thnk.ng/img/logo/logo-200.png
cover_image: /assets/images/blog-img-13.jpg

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-archives



# Site configuration for the Jekyll 2 Pagination Gem
pagination:
  enabled: true
  debug: true
  collection: 'posts'
  per_page: 6
  permalink: '/pages/:num/' # Pages are simple html files 
  title: ':title - page :num'
  limit: 0 
  sort_field: 'date'
  sort_reverse: true
  category: 'posts'
  tag: ''
  locale: '' 
  trail: 
    before: 2
    after: 
  extension: 'html'
  indexpage: 'index'

autopages:
  enabled: true
  categories: 
    layouts: 
      - 'category.html'
    title: 'Category -  :cat'
    permalink: '/category/:cat'
  collections:
    layouts: 
      - 'category.html'
    title: ' :coll' # :coll is replaced by the collection name
    permalink: '/:coll/'
    
  
  tags:
    layouts: 
      - 'tag.html'
    title: 'Tag - :tag' # :tag is replaced by the tag name
    permalink: '/tag/:tag'  
      
tag_page_layout: category
tag_page_dir: tag
tag_permalink_style: pretty

jekyll-archives:
  enabled: all
  layout: category
  permalinks:
    category: '/category/:name/'
 
collections:
  courses:
    title: Courses
    output: true
    permalink: /courses/:path/    
  instructors:
    title: Instructors
    output: true
    permalink: /instructors/:path/    
